### ISSUE TITLE
Use TFP pip package instead of `pip install .`?

### ISSUE THREAD

**Issue by csuter** [conda-forge/tensorflow-probability-feedstock#3]
Hi, I'm an engineer on the TFP team. We're collectively not super privy to conda, but appreciate your effort to make TFP available.

I'm concerned the current impl takes an unsupported approach to installing the code (modifying setup.py and running `pip install .`). It looks like the TensorFlow feedstock just installs the pip package from PyPI. Would you mind changing this one to do the same? As currently implemented, there's a greater risk of confusion about the user's system configuration when, e.g., folks file TFP bugs.

Thanks for your consideration.

**Comment by msarahan** [comment]
In general, it's advisable to build things from source.  We have our own toolchain configuration on each platform and especially with binary code, this helps iron out a lot of incompatibilities and establish a clear baseline for where software will run.  The Tensorflow feedstock is an exception to that rule, not the norm.  It is very much frowned on in this community to just "repack" other people's binaries, because you blindly inherit their compatibility bounds.  The repacks of Tensorflow here are only permissible because tensorflow is so incredibly time consuming to build from source.  The "defaults" packages do build tensorflow from source, and Anaconda spends significant time to accomplish that.  It is highly inadvisable to just use your builds from PyPI with a conda stack.  Sorry, but I recommend that you add something to your issue tracker that helps flag conda installations sooner, so that those issues can be identified more readily and redirected here.

Alternatively, you could help maintain this feedstock directly and ensure that it meets your organization's standards.  Trust me, we'd all love for installation problems with Tensorflow and friends to go away, but telling everyone to just use your wheels is not a complete solution.  This is an active area of discussion on the TF SIG build group: https://docs.google.com/document/d/1uYZK2jQtDUPpo3AHe18ZCH1jS9be9s8zR3axLR1SOG0/edit?ts=5c5b59f0#heading=h.7sjot6x53yvw

**Comment by jvdillon** [comment]
Hi @msarahan. I wonder to what extent your concerns apply to TFP vs TF.  Since TFP works for all versions of Python and has no source which isnt Python, it seems to me that the value add of a dedicated conda package for TFP is much lower than the value-add of a dedicated conda package for TF.  Thoughts?

**Comment by msarahan** [comment]
If someone uses pip to install TFP, then pip will satisfy TFP's requirements with wheels from PyPI.  If someone wanted to use conda's TF packages instead, they'd have to either ensure that TFP's requirements were satisfied before trying to install TFP with pip, or overwrite whatever TF pip installed for TFP.  Either way, you are requiring that two package managers act on the same space. That sucks.  If TFP was a standalone thing, your argument would be a lot stronger, but unfortunately, you do not stand alone, and regardless, it is much better to have environments be manageable with only one tool.

**Comment by jvdillon** [comment]
Before I ask a number of questions, are you saying there already is conda support for TF?

**Comment by msarahan** [comment]
yes.  I'm not sure what the support in conda-forge is.  It might be a repackage of the wheels, which is of limited value (just lets you use only conda to manage packages).  Anaconda (the defaults channel) has Tensorflow packages built from source.

**Comment by jvdillon** [comment]
If there is conda support which does not repackage the wheels then i agree with you. Failing that I do not agree with you because of the reasons listed. Possibly relevant notes:
- TFP doesnt even have a TF dependency on TF currently
- TFP pip deps can be ignored via `--no-dependencies`

FWIW, TFP has no dependencies which arent otherwise satisfied by TF except `decorator` and `cloudpickle`. It is very unlikely that we will add additional dependencies in the future.

**Comment by mayou36** [comment]
While repacking wheels may does not _seem_ like a large benefit, it is a **huge** one over not having them repacked: currently, any package that wants to have a conda build but depends on TFP is stuck with the current availability of it on conda. Repacked wheels makes them available on conda, that's a game changer

**Comment by djsutherland** [comment]
@mayou36 FYI: #26 just brought this into a state where the automated PRs now should easily keep things up to date. If you'd like to be added as a maintainer to push those through, you can just send a PR adding yourself to the list in `meta.yaml` and we'll happily add you. :)

**Comment by mayou36** [comment]
Hey, that is great to hear, many thanks for this! Indeed, I'll do that since we anyway have a dependency on it

**Comment by jonas-eschle** [comment]
This is resolved as we have TensorFlow and JAX both in conda, closing
